### ISSUE TITLE
Feature/api key

### ISSUE THREAD

**Issue by redbow26** [redbow26/pso2-ng-api#6]
# Api key

## Description

Add authentication by api key in the project.
A api key is stored to the database and bind to a user. 
We can create and delete a api key with grapqhl mutation only if we are a administrator.

## Task

- [ ] create api key model
- [ ] add api key authentication
- [ ] add grapqhl mutation to create a api key
- [ ] add graphql mutation to delete a api key
- [ ] secure other mutation
